#!/usr/bin/env bash
# =============================================================================
# init-grouper.sh
#
# First-time environment setup for the Grouper dev container.
# Called by devcontainer.json postCreateCommand on first container creation.
# Safe to re-run: all steps are idempotent.
# =============================================================================

set -euo pipefail

GROUPER_CONF_DIR="/workspace/grouper/grouper/conf"
GROUPER_DEV_CONF_DIR="/workspace/grouper-dev/conf"
GROUPER_BIN="/workspace/grouper/grouper/bin"

echo "==> [init-grouper] Starting Grouper dev environment setup..."

# ── 0. Maven settings.xml ────────────────────────────────────────────────────
# grouper-parent/pom.xml declares a "nexus-releases" repo at the Sonatype
# staging API (upload-only; returns 400 on GET). Mirror it to Maven Central
# so the JDT and Maven don't accumulate thousands of cached failures.
mkdir -p "$HOME/.m2"
ln -sf /workspace/grouper-dev/maven/settings.xml "$HOME/.m2/settings.xml"
echo "==> [init-grouper] Linked Maven settings.xml (nexus-releases mirror)."

# ── 1. Wait for PostgreSQL ────────────────────────────────────────────────────
echo "==> [init-grouper] Waiting for PostgreSQL at ${DB_HOST:-db}:${DB_PORT:-5432}..."
until pg_isready \
        -h "${DB_HOST:-db}" \
        -p "${DB_PORT:-5432}" \
        -U "${DB_USER:-grouper}" \
        -d "${DB_NAME:-grouper}" \
        -q 2>/dev/null; do
    echo "    PostgreSQL not ready yet, retrying in 5s..."
    sleep 5
done
echo "    PostgreSQL is up."

# ── 2. grouper.hibernate.properties ──────────────────────────────────────────
# The only generated config file — contains DB credentials from env vars.
HIBERNATE_PROPS="${GROUPER_CONF_DIR}/grouper.hibernate.properties"
echo "==> [init-grouper] Writing grouper.hibernate.properties..."
mkdir -p "${GROUPER_CONF_DIR}"
cat > "${HIBERNATE_PROPS}" <<EOF
# Generated by scripts/init-grouper.sh — do not commit this file.

hibernate.connection.url       = jdbc:postgresql://${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-grouper}
hibernate.connection.username  = ${DB_USER:-grouper}
hibernate.connection.password  = ${DB_PASSWORD:-grouper}
hibernate.dialect              = org.hibernate.dialect.PostgreSQL95Dialect
hibernate.connection.driver_class = org.postgresql.Driver

# Connection pool (appropriate for local dev, not production)
hibernate.c3p0.max_size        = 5
hibernate.c3p0.min_size        = 0
hibernate.c3p0.timeout         = 100
hibernate.c3p0.max_statements  = 0

# Allow automatic DDL upgrades up to any 7.x version (required for Tomcat startup).
# This is a ceiling: older branches (5.x/6.x) stay below it and are unaffected.
registry.auto.ddl.upToVersion = 7.*.*

# Enable the Grouper UI in this dev environment
grouper.is.ui = true

# Use Grouper's built-in HTTP Basic auth (passwords stored in grouper_password table)
grouper.is.ui.basicAuthn = true
EOF
echo "    Written: ${HIBERNATE_PROPS}"

# ── 3. Static config files (symlinked from grouper-dev/conf/) ─────────────────
# These files are tracked in grouper-dev/conf/ and symlinked into grouper/conf/
# so both GSH and the Tomcat deploy task find them in one place.
echo "==> [init-grouper] Symlinking static config files from grouper-dev/conf/..."
for src in "${GROUPER_DEV_CONF_DIR}"/*.properties "${GROUPER_DEV_CONF_DIR}"/log4j2.xml; do
    fname=$(basename "${src}")
    dest="${GROUPER_CONF_DIR}/${fname}"
    ln -sf "${src}" "${dest}"
    echo "    Linked: ${dest}"
done

# Also symlink log4j2.xml into Tomcat's conf dir so the -Dlog4j.configurationFile
# pointer in setenv.sh resolves correctly.
ln -sf "${GROUPER_DEV_CONF_DIR}/log4j2.xml" "${CATALINA_HOME}/conf/log4j2.xml"
echo "    Linked: ${CATALINA_HOME}/conf/log4j2.xml"

# ── 4. Tomcat setenv.sh ───────────────────────────────────────────────────────
# setenv.sh is sourced by catalina.sh before startup — this is the correct
# Tomcat hook for Grouper's Java 17 --add-opens and log4j config pointer.
echo "==> [init-grouper] Symlinking Tomcat setenv.sh..."
ln -sf /workspace/grouper-dev/tomcat/setenv.sh "${CATALINA_HOME}/bin/setenv.sh"
chmod +x /workspace/grouper-dev/tomcat/setenv.sh
echo "    Linked: ${CATALINA_HOME}/bin/setenv.sh"

# ── 5. Tomcat users ───────────────────────────────────────────────────────────
TOMCAT_USERS="${CATALINA_HOME}/conf/tomcat-users.xml"
TOMCAT_USERS_TMPL="${CATALINA_HOME}/conf/tomcat-users.xml.template"
if [ -f "${TOMCAT_USERS_TMPL}" ]; then
    echo "==> [init-grouper] Generating Tomcat users from template..."
    sed \
        -e "s|\${GROUPER_SYSTEM_PASSWORD}|${GROUPER_SYSTEM_PASSWORD:-changeme}|g" \
        -e "s|\${TEST_SUBJECT_PASSWORD}|${TEST_SUBJECT_PASSWORD:-changeme}|g" \
        "${TOMCAT_USERS_TMPL}" > "${TOMCAT_USERS}"
    echo "    Written: ${TOMCAT_USERS}"
fi

# ── 6. Initialize Grouper registry ───────────────────────────────────────────
# Only runs if the Maven build has already produced grouper.jar. On a fresh
# clone there is no build yet at postCreateCommand time, so this whole section
# is skipped and the environment is NOT yet usable — the schema and the
# GrouperSystem UI password both get created by the re-run after the first
# build. That re-run is the "Grouper: Init Registry + UI Password" task.
echo "==> [init-grouper] Checking Grouper registry..."

GROUPER_JAR=$(find /workspace/grouper/grouper -name "grouper*.jar" -path "*/target/*" 2>/dev/null | grep -v sources | grep -v tests | head -1 || true)

if [ -z "${GROUPER_JAR}" ]; then
    echo ""
    echo "    Skipping registry init — project hasn't been built yet."
    echo "    This is expected on a fresh clone. The UI will not accept a login"
    echo "    until this step runs, so after your first build completes:"
    echo "      Terminal > Run Task > Grouper: Init Registry + UI Password"
    echo ""
else
    SCHEMA_EXISTS=$(PGPASSWORD="${DB_PASSWORD:-grouper}" psql \
        -h "${DB_HOST:-db}" \
        -p "${DB_PORT:-5432}" \
        -U "${DB_USER:-grouper}" \
        -d "${DB_NAME:-grouper}" \
        -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='grouper_groups';" \
        2>/dev/null | tr -d ' ' || echo "0")

    if [ "${SCHEMA_EXISTS}" = "0" ]; then
        echo "==> [init-grouper] Registry not found — running gsh -registry -runscript..."
        # -noprompt: gsh otherwise asks y/n on stdin, which hangs or dies under
        # postCreateCommand and any other non-interactive run.
        # GROUPER_GSH_JVMARGS: no DISPLAY here, and gsh.sh only passes this
        # through rather than setting headless itself, so without it GSH dies on
        # an AWT/X11 library error.
        cd /workspace/grouper && GROUPER_GSH_JVMARGS="-Djava.awt.headless=true" \
            grouper/bin/gsh.sh -registry -runscript -noprompt
        echo "    Registry initialized."
    else
        echo "    Registry already initialized — skipping."
    fi

    # ── 6b. GrouperSystem UI password ────────────────────────────────────────
    # grouper.is.ui.basicAuthn = true means the UI validates against the
    # grouper_password table, so without this row the UI rejects every login.
    # GrouperPasswordSave upserts, so this is safe to re-run.
    echo "==> [init-grouper] Setting GrouperSystem UI password..."

    # The password is read from the environment inside GSH rather than
    # interpolated into the script body, so the plaintext never lands on disk
    # and never reaches the task terminal (GSH echoes the script it loads).
    # mktemp -d is mode 700; the whole directory goes on exit.
    GSH_TMPDIR=$(mktemp -d)
    trap 'rm -rf "${GSH_TMPDIR}"' EXIT
    GSH_SCRIPT="${GSH_TMPDIR}/set-grouper-password.gsh"
    GSH_OUT="${GSH_TMPDIR}/gsh-output.log"

    # System.out.println, not println: GSH is BeanShell, where a bare `println`
    # is a parse error. It failed silently before because the old invocation
    # discarded the exit status.
    cat > "${GSH_SCRIPT}" << 'GSHEOF'
new GrouperPasswordSave().assignUsername("GrouperSystem").assignPassword(System.getenv("GROUPER_INIT_UI_PASSWORD")).assignApplication(GrouperPassword.Application.UI).save();
System.out.println("[password] GrouperSystem UI password set.");
GSHEOF

    # Output goes to a file rather than through a pipe: `set -o pipefail` plus a
    # short-circuiting `grep -q` would SIGPIPE gsh and report a false failure.
    # And no trailing "|| true" — discarding gsh's exit status is what let a
    # broken UI login ship unnoticed.
    set +e
    (
        cd /workspace/grouper \
            && GROUPER_INIT_UI_PASSWORD="${GROUPER_SYSTEM_PASSWORD:-changeme}" \
               GROUPER_GSH_JVMARGS="-Djava.awt.headless=true" \
               grouper/bin/gsh.sh "${GSH_SCRIPT}"
    ) > "${GSH_OUT}" 2>&1
    GSH_RC=$?
    set -e

    if [ "${GSH_RC}" -ne 0 ] || ! grep -qF "[password] GrouperSystem UI password set." "${GSH_OUT}"; then
        echo "" >&2
        echo "ERROR: failed to set the GrouperSystem UI password (gsh exit ${GSH_RC})." >&2
        echo "       The registry may be initialized, but the UI will reject every login." >&2
        echo "       Full GSH output follows:" >&2
        cat "${GSH_OUT}" >&2
        exit 1
    fi
    echo "    GrouperSystem UI password set."
fi

# ── 7. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "==> [init-grouper] Setup complete."
echo ""
echo "    Next steps:"
echo "      1. Run: Maven: Build All (skip tests)  [Ctrl+Shift+B]"
echo "      2. Run: Deploy: UI to Tomcat"
echo "      3. Run: Grouper: Init Registry + UI Password"
echo "      4. Launch: Start Tomcat + Attach Debugger  [F5]"
echo "      5. Browse to: http://localhost:8080/grouper"
echo ""
